name: Release Pipeline

# Execution needs to be triggered manually at https://github.com/BetterDiscord/Installer/actions/workflows/release-pipeline.yml.

# This pipeline is pretty hard-coded and will deliver
# identical results no matter the branch it's run against.

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: The version label to be used for this release
        required: true

concurrency: development

jobs:
  prepare:
    name: Prepare Repo
    runs-on: ubuntu-latest
    outputs:
      old_version: ${{ steps.version_bump.outputs.old_version }}
      new_version: ${{ steps.version_bump.outputs.new_version }}
    steps:
    
      - name: checkout 'development'
        uses: actions/checkout@v2
        with:
          ref: 'development'
          fetch-depth: 0
          
      - uses: actions/upload-artifact@v2
        with:
          name: source
          path: |
            ./*
            !.git/config
          
  

  # Download source artifact, build, upload build artifact.
  # Runs once on each release platform.
  build:
    name: Build
    needs:
      - prepare
    strategy:
      fail-fast: true
      matrix:
        os:
          # ordered by how fast they build (muh cosmetics)
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:

      - uses: actions/download-artifact@v2
        with:
          name: source

      - run: yarn install && yarn dist

      - uses: actions/upload-artifact@v2
        if: ${{ success() && matrix.os == 'windows-latest' }}
        with:
          name: build
          path: dist/BetterDiscord-Windows.exe
          if-no-files-found: error
          NEW_VERSION: ${{ needs.prepare.outputs.new_version }}
          NAKED_INPUT_VERSION_TAG: ${{ github.event.inputs.version_tag }}
          RELEASE_NOTES_TEMPLATE_LOCATION: .github/RELEASE_TEMPLATE.md
