name: Release Pipeline

# Execution needs to be triggered manually at https://github.com/BetterDiscord/Installer/actions/workflows/release-pipeline.yml.

# This pipeline is pretty hard-coded and will deliver
# identical results no matter the branch it's run against.

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: The version label to be used for this release
        required: true

concurrency: release

jobs:
  prepare:
    name: Prepare Repo
    runs-on: ubuntu-latest
    outputs:
      old_version: ${{ steps.version_bump.outputs.old_version }}
      new_version: ${{ steps.version_bump.outputs.new_version }}
    steps:
      - uses: actions/upload-artifact@v2
        with:
          name: source
          path: |
            ./*
            !.git/config
          
  

  # Download source artifact, build, upload build artifact.
  # Runs once on each release platform.
  build:
    name: Build
    strategy:
      fail-fast: true
      matrix:
        os:
          # ordered by how fast they build (muh cosmetics)
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:

      - uses: actions/download-artifact@v2
        with:
          name: source

      - run: yarn install && yarn dist
        env:
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}

      - uses: actions/upload-artifact@v2
        if: ${{ success() && matrix.os == 'ubuntu-latest' }}
        with:
          name: build
          path: dist/BetterDiscord-Linux.AppImage
          if-no-files-found: error

      - uses: actions/upload-artifact@v2
        if: ${{ success() && matrix.os == 'windows-latest' }}
        with:
          name: build
          path: dist/BetterDiscord-Windows.exe
          if-no-files-found: error

      - if: ${{ success() && matrix.os == 'macos-latest' }}
        run: mv -f dist/BetterDiscord-*-mac.zip dist/BetterDiscord-Mac.zip
      - if: ${{ success() && matrix.os == 'macos-latest' }}
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist/BetterDiscord-Mac.zip
          if-no-files-found: error

  # Download build artifact, do github release.
  publish:
    name: Draft Release
    needs:
      - build
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          ref: ${{ needs.push_changes.outputs.sha_1 }}

      - name: authenticate gh-cli
        run: echo "$GITHUB_TOKEN_STUPIDO" | gh auth login --with-token
        env:
          GITHUB_TOKEN_STUPIDO: ${{ secrets.CI_PAT }}

      - uses: actions/download-artifact@v2
        with:
          name: build

      - name: upload release draft
        run: |
          gh release create "$NEW_VERSION" --draft --title "$NEW_VERSION" --target "$SHA1" --generate-notes \
            "BetterDiscord-Linux.AppImage#Linux (AppImage)" \
            "BetterDiscord-Mac.zip#Mac OS (Zip)" \
            "BetterDiscord-Windows.exe#Windows (Exe)"
        env:
          SHA1: ${{ needs.push_changes.outputs.sha_1 }}
          OLD_VERSION: ${{ needs.prepare.outputs.old_version }}
          NEW_VERSION: ${{ needs.prepare.outputs.new_version }}
          NAKED_INPUT_VERSION_TAG: ${{ github.event.inputs.version_tag }}
          RELEASE_NOTES_TEMPLATE_LOCATION: .github/RELEASE_TEMPLATE.md
